### PR TITLE
Django Tutorial Part 5: Creating our home page

### PR DESCRIPTION
**Pull request by hoanghaiphongg**
Ready

### CODE REVIEW

**Comment by hoanghaiphongg** [comment]
Ready

**Review by thaodtd-0665 — COMMENTED** [review]
pull này conflict code rồi em

**Comment by hoanghaiphongg** [comment]
Ready

**Comment by hoanghaiphongg** [comment]
Ready

**Comment by hoanghaiphongg** [comment]
Ready

**Comment by huongnt-2545** [comment]
merged

**Pull request merged**
